# Generated by Django 5.0 on 2023-12-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleFontSize', models.CharField(default=12, max_length=20)),
                ('titleFontColor', models.CharField(default='#000', max_length=20)),
                ('bodyFontColor', models.CharField(default='#000', max_length=20)),
                ('backgroundColor', models.CharField(default='#fff', max_length=20)),
                ('cornerRadius', models.CharField(default=3, max_length=20)),
                ('position', models.CharField(default='top', max_length=20)),
            ],
        ),
    ]
