# Generated by Django 5.0 on 2023-12-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_exelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='exelfile',
            name='name',
            field=models.CharField(default='nam', max_length=50),
            preserve_default=False,
        ),
    ]
