# Generated by Django 5.0 on 2023-12-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_exelfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exelfile',
            name='name',
        ),
    ]
