# Generated by Django 5.0 on 2023-12-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_remove_exelfile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exelfile',
        ),
    ]
